version: 2.1

jobs:
  build_test:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: Install npm dependencies
          command: npm install
      - run:
          name: Run ESLint (SAST)
          command: npx eslint .
      - run:
          name: Run Snyk (SCA)
          command: |
            npm install -g snyk
            snyk auth $SNYK_TOKEN
            snyk test

  build_docker_image:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
          docker_layer_caching: true
      - run:
          name: Build Docker image
          command: |
            docker build -t nodejswebapp1 -t anshumaan10/nodejswebapp1:latest .
            echo $DOCKER_PASSWORD | docker login -u anshumaan10 --password-stdin
            docker push anshumaan10/nodejswebapp1:latest

  scan_docker_image:
    docker:
      - image: aquasec/trivy:latest
    steps:
      - run:
          name: Install Docker CLI
          command: |
            apt-get update
            apt-get install -y docker.io
      - run:
          name: Scan Docker image with Trivy
          command: |
            docker pull anshumaan10/nodejswebapp1:latest
            trivy image anshumaan10/nodejswebapp1:latest

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_test
      - build_docker_image
      - scan_docker_image:
          requires:
            - build_docker_image
